### ISSUE TITLE
Chapter reading order to go along with problem sets?

### ISSUE THREAD

**Issue by mdempsky** [mit-frap/spring20#4]
Is there a recommended reading order to go along with the problem sets? E.g., does the MIT class have a weekly reading syllabus or something that could be shared with non-MIT-students too?

I've got a nascent, independent FRAP study group going at work now. We're trying to read through FRAP and complete these assignments (just reviewed pset1 solutions today), but the assignments don't appear to exactly line up with the book chapters.

As best I can tell from skimming the problems and having read ahead in the book a little:

- Pset 1 somewhat depends on chapter 2
- Pset 2 is just pure Coq / math practice
- Psets 3 and 4 somewhat depend on chapter 3 and Polymorphism.v
- Pset 5 depends on chapters 4 and 7; but chapter 7 also somewhat depends on chapter 5.
- Pset 6 depends on chapter 8 (which definitely depends on chapter 5, and maybe chapter 6 too)

Thanks!

**Comment by samuelgruetter** [comment]
If you go to https://frap.csail.mit.edu/ and click on the "Calendar" tab, you should see the schedule, which is public. There you can see which lectures happened before a Pset was released, and by clicking on a lecture, it will show you a summary of what @achlipala covered in that lecture, and indicate the *Related Reading* in the FRAP pdf and *Related Coq Code* in the FRAP repo.

**Comment by mdempsky** [comment]
Ah, thank you very much! That's exactly what I was looking for.

I'd looked at the course website many times now, but I guess I never noticed the "calendar" tab.
